In [1]:
import requests

In [2]:
%pip install xlrd

Collecting xlrd
  Downloading xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
     |████████████████████████████████| 96 kB 6.5 MB/s
Installing collected packages: xlrd
Successfully installed xlrd-2.0.1
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
import xlrd

In [33]:
df_bcra = pd.read_excel('panhis.xls', sheet_name = 'Cuadro',  engine = 'xlrd', header = [25], dtype= {'bcrafec':str} )

    engine : str, default None
        If io is not a buffer or path, this must be set to identify io.
        Supported engines: "xlrd", "openpyxl", "odf", "pyxlsb", default "xlrd".
        Engine compatibility :
        - "xlrd" supports most old/new Excel file formats.
        - "openpyxl" supports newer Excel file formats.
        - "odf" supports OpenDocument file formats (.odf, .ods, .odt).
        - "pyxlsb" supports Binary Excel files.
     
     header : int, list of int, default 0
        Row (0-indexed) to use for the column labels of the parsed
        DataFrame. If a list of integers is passed those row positions will
        be combined into a ``MultiIndex``. Use None if there is no header.
        
    dtype : Type name or dict of column -> type, default None
        Data type for data or columns. E.g. {'a': np.float64, 'b': np.int32}
        Use `object` to preserve data as stored in Excel and not interpret dtype.
        If converters are specified, they will be applied INSTEAD
        of dtype conversion.

In [34]:
df_bcra = df_bcra.drop(0)
df_bcra = df_bcra.drop(['Unnamed: 4', 'Unnamed: 5', 'sisobs', 'sismes' , 'Unnamed: 3'], axis =1)
df_bcra= df_bcra.rename({'bcrafec':'Date'}, axis=1)

In [35]:
df_bcra['Date'] = pd.to_datetime(df_bcra['Date'], format = '%Y.%m', errors='coerce')

In [36]:
df_bcra['Date'] = df_bcra['Date'].dt.to_period('M')

In [37]:
df_bcra

,Date,pan30,pan31,pan32,pan33,pan34,pan45,pan46,pan37,pan38,...,pan18,pan27,pan19,pan20,pan25,pan26,pan21,pan22,pan23,pan24
1,1940-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1940-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1940-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1940-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1940-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1061,2021-08,4.021268e+06,2.927784e+06,2.139383e+06,788401.000000,1.093484e+06,2.030824e+06,0.0,1.894607e+06,1.894607e+06,...,0.373811,1.89,30.44,0,.,.,40.96,0.0,24.84,0.0
1062,2021-09,4.079986e+06,2.937229e+06,2.164627e+06,772602.166667,1.142758e+06,2.081587e+06,0.0,2.027147e+06,2.027150e+06,...,0.378059,4.91,31.3,3,.,.,41.29,0.0,26.43,0.0
1063,2021-01,4.180978e+06,3.009316e+06,2.216118e+06,793197.354839,1.171662e+06,2.105131e+06,0.0,2.122027e+06,2.122027e+06,...,0.377245,4.98,31.04,0,.,.,41.53,0.0,25.99,0.0
1064,2021-11,4.350273e+06,3.148095e+06,2.293738e+06,854357.100000,1.202178e+06,2.073820e+06,0.0,2.250137e+06,2.250137e+06,...,0.375207,0,31.13,0,.,.,41.06,0.0,25.26,0.0
1065,2021-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,.,.,NaN,NaN,NaN,NaN

http://www.bcra.gov.ar/PublicacionesEstadisticas/Cuadros_estandarizados_series_estadisticas_i.asp?prevPage=stat